adminUser: admin
adminPassword: CHANGE_ME # to ease testing of grafana, might be better to use self-generated password

service:
  type: ClusterIP

ingress:
  enabled: true
  hosts:
    - grafana.local

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.monitoring.svc.cluster.local
        access: proxy

persistence:
  enabled: true
  storageClassName: local-path
  size: 2Gi
