server:
  retention: "3d"

  persistentVolume:
    size: 2Gi
    # enable: false # Not enough storage on my VM so for now, bot giving persistent storage

alertmanager:
  persistentVolume:
    size: 1Gi
    # enable: false
