server:
  retention: "3d"

  persistentVolume:
    enable: true

prometheusSpec:
  storageSpec:
    volumeClaimTemplate:
      spec:
        accessModes: ["ReadWriteOnce"]
        ressources:
          requests:
            storage: 2Gi
          limits:
            storage: 10Gi

serverFiles:
  prometheus.yml:
    scrape_configs:
      - job_name: focalboard
        static_configs:
          - targets:
              - focalboard-service.focalboard.svc.cluster.local:9092
alertmanager:
  persistentVolume:
    size: 1Gi
    enable: true
