- name: Install k3s
  hosts: debianAzure
  become: yes

  tasks:
    - name: Install curl
      apt:
        name: curl
        state: present
        update_cache: yes

    - name: Install K3s
      shell: |
        curl -sfL https://get.k3s.io | \
        INSTALL_K3S_EXEC="server --tls-san {{ inventory_hostname }}" sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Wait for K3s
      command: kubectl get nodes
      register: result
      retries: 20
      delay: 10
      until: result.rc == 0

- name: Install Helm
  hosts: debianAzure 
  become: yes
  tasks:
    - name: Install curl (if not already installed)
      package:
        name: curl
        state: present

    - name: Download Helm installation script
      get_url:
        url: https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
        dest: /tmp/get_helm.sh
        mode: '0755'

    - name: Run Helm installation script
      command: /tmp/get_helm.sh
      args:
        creates: /usr/local/bin/helm
      register: helm_install_result
      changed_when: false

    - name: Add /usr/local/bin to PATH
      lineinfile:
        path: ~/.bashrc
        line: 'export PATH=$PATH:/usr/local/bin'
      when: helm_install_result.rc == 0

- name: Fetch kubeconfig #Use for install App with Terraform inside ../kubernetes repo
  hosts: debianAzure
  become: yes
  tasks:
    - name: Get k3s cloud VM condig
      fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: ../kubernetes/cloud-kubeconfig
        flat: yes

- name: Install Argo-Server
  hosts: debianAzure
  become: yes
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  tasks:  
    - name: Add Argo Helm repo
      shell: |
        helm repo add argo https://argoproj.github.io/argo-helm
        helm repo update

    - name: Install Argo CD
      shell: |
        helm upgrade --install argocd argo/argo-cd \
        --namespace argocd \
         --create-namespace

    - name: Bootstrap Argo CD
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml
      command: >
        kubectl apply -f
        https://raw.githubusercontent.com/cmoibssld/cloud-work/gitops/bootstrap/argocd-origin.yaml

