apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: focalboard-ingress
  namespace: "{{ .Release.Namespace }}"
spec:
  ingressClassName: traefik
  rules:
    - host: {{ .Values.server.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend: 
              service:
                name: focalboard-service
                port:
                  number: {{ .Values.server.port }}
