image:
  repository: heywoodlh/focalboard
  tag: a84bbb6

server:
  hostname: board.local
  root: http://board.local
  port: 8000
  port_target: 8000
  useSSL: false

prometheusPort: 9092  

postgres:
  auth:
    username: CHANGE_ME
    password: CHANGE_ME_DONT_COMMIT
    database: CHANGE_ME
  global:
    postgresql:
      fullnameOverride: postgres # overrides chart name one of the solution to get correct connection and DNS replacement inside focalboard config
