apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: "{{ .Release.Namespace }}"
data:
  POSTGRES_DB: "{{ .Values.postgres.name }}"
  POSTGRES_USER: "{{ .Values.postgres.user }}"
