apiVersion: v1
kind: Service
metadata:
  name: focalboard-service
  namespace: "{{ .Release.Namespace }}"
spec:
  selector:
    app: focalboard
  ports:
    - port: {{ .Values.server.port }}
      targetPort: {{ .Values.server.port_target }}
  type: ClusterIP
